import { detachAndFreezeReplayData } from "../../sim/replay/replayOwnership.ts";
import type { BuildTemplate, BuildTemplateClusterRole } from "./botContracts.ts";

const STARTER_TEMPLATE: BuildTemplate = {
  templateVersion: 1,
  id: "starter-serial",
  baseTemplateId: null,
  purpose: "A minimal serial vacuum-tube computer assembled from the starting inventory.",
  requiredResearchIds: [],
  modules: [
    {
      key: "power",
      definitionId: "module-power-distribution",
      position: { x: 0, y: 0 },
      rotation: 0,
    },
    {
      key: "logic",
      definitionId: "module-vacuum-tube-logic",
      position: { x: 4, y: 0 },
      rotation: 0,
    },
    { key: "control", definitionId: "module-control-unit", position: { x: 8, y: 0 }, rotation: 0 },
    {
      key: "memory",
      definitionId: "module-accumulator-register",
      position: { x: 12, y: 0 },
      rotation: 0,
    },
    {
      key: "input",
      definitionId: "module-punch-card-reader",
      position: { x: 4, y: 4 },
      rotation: 0,
    },
  ],
  routes: [
    {
      key: "power-logic",
      kind: "power",
      from: { moduleKey: "power", portId: "power-out-east" },
      to: { moduleKey: "logic", portId: "power-in-west" },
      path: [
        { x: 1, y: 0 },
        { x: 2, y: 0 },
        { x: 3, y: 0 },
        { x: 4, y: 0 },
      ],
    },
    {
      key: "power-control",
      kind: "power",
      from: { moduleKey: "power", portId: "power-out-south" },
      to: { moduleKey: "control", portId: "power-in-west" },
      path: [
        { x: 0, y: 1 },
        { x: 0, y: 2 },
        { x: 1, y: 2 },
        { x: 2, y: 2 },
        { x: 3, y: 2 },
        { x: 4, y: 2 },
        { x: 5, y: 2 },
        { x: 6, y: 2 },
        { x: 7, y: 2 },
        { x: 7, y: 1 },
        { x: 7, y: 0 },
        { x: 8, y: 0 },
      ],
    },
    {
      key: "power-memory",
      kind: "power",
      from: { moduleKey: "power", portId: "power-out-south" },
      to: { moduleKey: "memory", portId: "power-in-south" },
      path: [
        { x: 0, y: 1 },
        { x: 0, y: 2 },
        { x: 1, y: 2 },
        { x: 2, y: 2 },
        { x: 3, y: 2 },
        { x: 4, y: 2 },
        { x: 5, y: 2 },
        { x: 6, y: 2 },
        { x: 7, y: 2 },
        { x: 8, y: 2 },
        { x: 9, y: 2 },
        { x: 10, y: 2 },
        { x: 11, y: 2 },
        { x: 12, y: 2 },
        { x: 12, y: 1 },
      ],
    },
    {
      key: "power-input",
      kind: "power",
      from: { moduleKey: "power", portId: "power-out-south" },
      to: { moduleKey: "input", portId: "power-in-west" },
      path: [
        { x: 0, y: 1 },
        { x: 0, y: 2 },
        { x: 0, y: 3 },
        { x: 1, y: 3 },
        { x: 2, y: 3 },
        { x: 3, y: 3 },
        { x: 3, y: 4 },
        { x: 4, y: 4 },
      ],
    },
    {
      key: "input-logic",
      kind: "data",
      from: { moduleKey: "input", portId: "data-out-east" },
      to: { moduleKey: "logic", portId: "data-east" },
      path: [
        { x: 5, y: 4 },
        { x: 6, y: 4 },
        { x: 6, y: 3 },
        { x: 6, y: 2 },
        { x: 6, y: 1 },
        { x: 6, y: 0 },
        { x: 5, y: 0 },
      ],
    },
    {
      key: "logic-control",
      kind: "data",
      from: { moduleKey: "logic", portId: "data-east" },
      to: { moduleKey: "control", portId: "data-west" },
      path: [
        { x: 5, y: 0 },
        { x: 6, y: 0 },
        { x: 7, y: 0 },
        { x: 8, y: 0 },
      ],
    },
    {
      key: "control-memory",
      kind: "data",
      from: { moduleKey: "control", portId: "data-east" },
      to: { moduleKey: "memory", portId: "data-west" },
      path: [
        { x: 9, y: 0 },
        { x: 10, y: 0 },
        { x: 11, y: 0 },
        { x: 12, y: 0 },
      ],
    },
  ],
  clusterRoles: {
    "task-primary": ["logic", "control", "memory"],
    "research-primary": ["logic", "control", "memory"],
    "benchmark-sustained": ["logic", "control"],
    "benchmark-peak": ["logic", "control"],
    "blueprint-selection": ["power", "logic", "control", "memory", "input"],
  } satisfies Readonly<Record<BuildTemplateClusterRole, readonly string[]>>,
};

const EXPANDED_TEMPLATE: BuildTemplate = {
  templateVersion: 1,
  id: "expanded-balanced",
  baseTemplateId: "starter-serial",
  purpose: "An incremental arithmetic extension for larger research and finite tasks.",
  requiredResearchIds: ["research-stable-power-distribution"],
  modules: [
    {
      key: "arithmetic",
      definitionId: "module-arithmetic-unit",
      position: { x: 2, y: 8 },
      rotation: 0,
    },
    {
      key: "arithmetic-2",
      definitionId: "module-arithmetic-unit",
      position: { x: 4, y: 12 },
      rotation: 0,
    },
    {
      key: "memory-2",
      definitionId: "module-accumulator-register",
      position: { x: 16, y: 0 },
      rotation: 0,
    },
    {
      key: "power-benchmark",
      definitionId: "module-power-distribution",
      position: { x: 20, y: 0 },
      rotation: 0,
    },
    {
      key: "arithmetic-3",
      definitionId: "module-arithmetic-unit",
      position: { x: 9, y: 12 },
      rotation: 0,
    },
    {
      key: "arithmetic-4",
      definitionId: "module-arithmetic-unit",
      position: { x: 14, y: 12 },
      rotation: 0,
    },
  ],
  routes: [
    {
      key: "power-memory-2",
      kind: "power",
      from: { moduleKey: "power", portId: "power-out-south" },
      to: { moduleKey: "memory-2", portId: "power-in-south" },
      path: [
        { x: 0, y: 1 },
        { x: 0, y: 2 },
        { x: 1, y: 2 },
        { x: 2, y: 2 },
        { x: 3, y: 2 },
        { x: 4, y: 2 },
        { x: 5, y: 2 },
        { x: 6, y: 2 },
        { x: 7, y: 2 },
        { x: 8, y: 2 },
        { x: 9, y: 2 },
        { x: 10, y: 2 },
        { x: 11, y: 2 },
        { x: 12, y: 2 },
        { x: 13, y: 2 },
        { x: 14, y: 2 },
        { x: 15, y: 2 },
        { x: 16, y: 2 },
        { x: 16, y: 1 },
      ],
    },
    {
      key: "memory-memory-2",
      kind: "data",
      from: { moduleKey: "memory", portId: "data-east" },
      to: { moduleKey: "memory-2", portId: "data-west" },
      path: [
        { x: 12, y: 0 },
        { x: 13, y: 0 },
        { x: 14, y: 0 },
        { x: 15, y: 0 },
        { x: 16, y: 0 },
      ],
    },
    {
      key: "power-arithmetic",
      kind: "power",
      from: { moduleKey: "power", portId: "power-out-south" },
      to: { moduleKey: "arithmetic", portId: "power-in-west" },
      path: [
        { x: 0, y: 1 },
        { x: 0, y: 2 },
        { x: 0, y: 3 },
        { x: 0, y: 4 },
        { x: 0, y: 5 },
        { x: 0, y: 6 },
        { x: 0, y: 7 },
        { x: 0, y: 8 },
        { x: 1, y: 8 },
        { x: 2, y: 8 },
      ],
    },
    {
      key: "memory-arithmetic",
      kind: "data",
      from: { moduleKey: "memory", portId: "data-east" },
      to: { moduleKey: "arithmetic", portId: "data-in-north" },
      path: [
        { x: 12, y: 0 },
        { x: 13, y: 0 },
        { x: 13, y: 1 },
        { x: 13, y: 2 },
        { x: 13, y: 3 },
        { x: 13, y: 4 },
        { x: 13, y: 5 },
        { x: 13, y: 6 },
        { x: 13, y: 7 },
        { x: 12, y: 7 },
        { x: 11, y: 7 },
        { x: 10, y: 7 },
        { x: 9, y: 7 },
        { x: 8, y: 7 },
        { x: 7, y: 7 },
        { x: 6, y: 7 },
        { x: 5, y: 7 },
        { x: 4, y: 7 },
        { x: 3, y: 7 },
        { x: 2, y: 7 },
        { x: 2, y: 8 },
      ],
    },
    {
      key: "arithmetic-memory",
      kind: "data",
      from: { moduleKey: "arithmetic", portId: "data-out-east" },
      to: { moduleKey: "memory", portId: "data-west" },
      path: [
        { x: 3, y: 9 },
        { x: 4, y: 9 },
        { x: 5, y: 9 },
        { x: 6, y: 9 },
        { x: 7, y: 9 },
        { x: 8, y: 9 },
        { x: 9, y: 9 },
        { x: 10, y: 9 },
        { x: 11, y: 9 },
        { x: 11, y: 8 },
        { x: 11, y: 7 },
        { x: 11, y: 6 },
        { x: 11, y: 5 },
        { x: 11, y: 4 },
        { x: 11, y: 3 },
        { x: 11, y: 2 },
        { x: 11, y: 1 },
        { x: 11, y: 0 },
        { x: 12, y: 0 },
      ],
    },
    {
      key: "power-arithmetic-2",
      kind: "power",
      from: { moduleKey: "power", portId: "power-out-south" },
      to: { moduleKey: "arithmetic-2", portId: "power-in-west" },
      path: [
        { x: 0, y: 1 },
        { x: 0, y: 2 },
        { x: 0, y: 3 },
        { x: 0, y: 4 },
        { x: 0, y: 5 },
        { x: 0, y: 6 },
        { x: 0, y: 7 },
        { x: 0, y: 8 },
        { x: 0, y: 9 },
        { x: 0, y: 10 },
        { x: 0, y: 11 },
        { x: 0, y: 12 },
        { x: 1, y: 12 },
        { x: 2, y: 12 },
        { x: 3, y: 12 },
        { x: 4, y: 12 },
      ],
    },
    {
      key: "memory-arithmetic-2",
      kind: "data",
      from: { moduleKey: "memory", portId: "data-east" },
      to: { moduleKey: "arithmetic-2", portId: "data-in-north" },
      path: [
        { x: 12, y: 0 },
        { x: 13, y: 0 },
        { x: 13, y: 1 },
        { x: 13, y: 2 },
        { x: 13, y: 3 },
        { x: 13, y: 4 },
        { x: 13, y: 5 },
        { x: 13, y: 6 },
        { x: 13, y: 7 },
        { x: 13, y: 8 },
        { x: 13, y: 9 },
        { x: 12, y: 9 },
        { x: 11, y: 9 },
        { x: 10, y: 9 },
        { x: 9, y: 9 },
        { x: 8, y: 9 },
        { x: 7, y: 9 },
        { x: 6, y: 9 },
        { x: 5, y: 9 },
        { x: 4, y: 9 },
        { x: 4, y: 10 },
        { x: 4, y: 11 },
        { x: 4, y: 12 },
      ],
    },
    {
      key: "arithmetic-2-memory",
      kind: "data",
      from: { moduleKey: "arithmetic-2", portId: "data-out-east" },
      to: { moduleKey: "memory", portId: "data-west" },
      path: [
        { x: 5, y: 13 },
        { x: 6, y: 13 },
        { x: 6, y: 14 },
        { x: 7, y: 14 },
        { x: 8, y: 14 },
        { x: 9, y: 14 },
        { x: 10, y: 14 },
        { x: 11, y: 14 },
        { x: 11, y: 13 },
        { x: 11, y: 12 },
        { x: 11, y: 11 },
        { x: 11, y: 10 },
        { x: 11, y: 9 },
        { x: 11, y: 8 },
        { x: 11, y: 7 },
        { x: 11, y: 6 },
        { x: 11, y: 5 },
        { x: 11, y: 4 },
        { x: 11, y: 3 },
        { x: 11, y: 2 },
        { x: 11, y: 1 },
        { x: 11, y: 0 },
        { x: 12, y: 0 },
      ],
    },
    {
      key: "power-arithmetic-3",
      kind: "power",
      from: { moduleKey: "power-benchmark", portId: "power-out-south" },
      to: { moduleKey: "arithmetic-3", portId: "power-in-west" },
      path: [
        { x: 20, y: 1 },
        { x: 20, y: 2 },
        { x: 21, y: 2 },
        { x: 22, y: 2 },
        { x: 22, y: 3 },
        { x: 22, y: 4 },
        { x: 22, y: 5 },
        { x: 22, y: 6 },
        { x: 22, y: 7 },
        { x: 22, y: 8 },
        { x: 22, y: 9 },
        { x: 22, y: 10 },
        { x: 22, y: 11 },
        { x: 21, y: 11 },
        { x: 20, y: 11 },
        { x: 19, y: 11 },
        { x: 18, y: 11 },
        { x: 17, y: 11 },
        { x: 16, y: 11 },
        { x: 15, y: 11 },
        { x: 14, y: 11 },
        { x: 13, y: 11 },
        { x: 12, y: 11 },
        { x: 11, y: 11 },
        { x: 10, y: 11 },
        { x: 9, y: 11 },
        { x: 8, y: 11 },
        { x: 8, y: 12 },
        { x: 9, y: 12 },
      ],
    },
    {
      key: "power-arithmetic-4",
      kind: "power",
      from: { moduleKey: "power-benchmark", portId: "power-out-south" },
      to: { moduleKey: "arithmetic-4", portId: "power-in-west" },
      path: [
        { x: 20, y: 1 },
        { x: 20, y: 2 },
        { x: 21, y: 2 },
        { x: 22, y: 2 },
        { x: 22, y: 3 },
        { x: 22, y: 4 },
        { x: 22, y: 5 },
        { x: 22, y: 6 },
        { x: 22, y: 7 },
        { x: 22, y: 8 },
        { x: 22, y: 9 },
        { x: 22, y: 10 },
        { x: 21, y: 10 },
        { x: 20, y: 10 },
        { x: 19, y: 10 },
        { x: 18, y: 10 },
        { x: 17, y: 10 },
        { x: 16, y: 10 },
        { x: 15, y: 10 },
        { x: 14, y: 10 },
        { x: 13, y: 10 },
        { x: 13, y: 11 },
        { x: 13, y: 12 },
        { x: 14, y: 12 },
      ],
    },
    {
      key: "memory-arithmetic-3",
      kind: "data",
      from: { moduleKey: "memory", portId: "data-east" },
      to: { moduleKey: "arithmetic-3", portId: "data-in-north" },
      path: [
        { x: 12, y: 0 },
        { x: 13, y: 0 },
        { x: 13, y: 1 },
        { x: 13, y: 2 },
        { x: 13, y: 3 },
        { x: 13, y: 4 },
        { x: 13, y: 5 },
        { x: 13, y: 6 },
        { x: 13, y: 7 },
        { x: 13, y: 8 },
        { x: 13, y: 9 },
        { x: 13, y: 10 },
        { x: 12, y: 10 },
        { x: 11, y: 10 },
        { x: 10, y: 10 },
        { x: 9, y: 10 },
        { x: 9, y: 11 },
        { x: 9, y: 12 },
      ],
    },
    {
      key: "arithmetic-3-memory",
      kind: "data",
      from: { moduleKey: "arithmetic-3", portId: "data-out-east" },
      to: { moduleKey: "memory", portId: "data-west" },
      path: [
        { x: 10, y: 13 },
        { x: 11, y: 13 },
        { x: 11, y: 12 },
        { x: 11, y: 11 },
        { x: 11, y: 10 },
        { x: 11, y: 9 },
        { x: 11, y: 8 },
        { x: 11, y: 7 },
        { x: 11, y: 6 },
        { x: 11, y: 5 },
        { x: 11, y: 4 },
        { x: 11, y: 3 },
        { x: 11, y: 2 },
        { x: 11, y: 1 },
        { x: 11, y: 0 },
        { x: 12, y: 0 },
      ],
    },
    {
      key: "memory-arithmetic-4",
      kind: "data",
      from: { moduleKey: "memory", portId: "data-east" },
      to: { moduleKey: "arithmetic-4", portId: "data-in-north" },
      path: [
        { x: 12, y: 0 },
        { x: 13, y: 0 },
        { x: 13, y: 1 },
        { x: 13, y: 2 },
        { x: 13, y: 3 },
        { x: 13, y: 4 },
        { x: 13, y: 5 },
        { x: 13, y: 6 },
        { x: 13, y: 7 },
        { x: 13, y: 8 },
        { x: 13, y: 9 },
        { x: 13, y: 10 },
        { x: 13, y: 11 },
        { x: 14, y: 11 },
        { x: 14, y: 12 },
      ],
    },
    {
      key: "arithmetic-4-memory",
      kind: "data",
      from: { moduleKey: "arithmetic-4", portId: "data-out-east" },
      to: { moduleKey: "memory", portId: "data-west" },
      path: [
        { x: 15, y: 13 },
        { x: 16, y: 13 },
        { x: 16, y: 14 },
        { x: 15, y: 14 },
        { x: 14, y: 14 },
        { x: 13, y: 14 },
        { x: 12, y: 14 },
        { x: 11, y: 14 },
        { x: 11, y: 13 },
        { x: 11, y: 12 },
        { x: 11, y: 11 },
        { x: 11, y: 10 },
        { x: 11, y: 9 },
        { x: 11, y: 8 },
        { x: 11, y: 7 },
        { x: 11, y: 6 },
        { x: 11, y: 5 },
        { x: 11, y: 4 },
        { x: 11, y: 3 },
        { x: 11, y: 2 },
        { x: 11, y: 1 },
        { x: 11, y: 0 },
        { x: 12, y: 0 },
      ],
    },
  ],
  clusterRoles: {
    "task-primary": [
      "memory",
      "memory-2",
      "arithmetic",
      "arithmetic-2",
      "arithmetic-3",
      "arithmetic-4",
    ],
    "research-primary": ["memory", "arithmetic", "arithmetic-2"],
    "benchmark-sustained": ["logic", "arithmetic", "arithmetic-2"],
    "benchmark-peak": ["logic", "arithmetic", "arithmetic-2"],
    "blueprint-selection": ["arithmetic", "arithmetic-2"],
  } satisfies Readonly<Record<BuildTemplateClusterRole, readonly string[]>>,
};

const COOLED_TEMPLATE: BuildTemplate = {
  templateVersion: 1,
  id: "cooled-benchmark",
  baseTemplateId: "expanded-balanced",
  purpose: "A cooling extension that makes sustained and peak benchmark runs possible.",
  requiredResearchIds: ["research-delay-line-memory", "research-vacuum-tube-reliability"],
  modules: [
    {
      key: "delay-memory",
      definitionId: "module-delay-line-memory",
      position: { x: 15, y: 4 },
      rotation: 0,
    },
    {
      key: "arithmetic-5",
      definitionId: "module-arithmetic-unit",
      position: { x: 19, y: 12 },
      rotation: 0,
    },
    {
      key: "room-cooling",
      definitionId: "module-room-cooling",
      position: { x: 18, y: 8 },
      rotation: 0,
    },
  ],
  routes: [
    {
      key: "power-delay-memory",
      kind: "power",
      from: { moduleKey: "power-benchmark", portId: "power-out-south" },
      to: { moduleKey: "delay-memory", portId: "power-in-west" },
      path: [
        { x: 20, y: 1 },
        { x: 20, y: 2 },
        { x: 19, y: 2 },
        { x: 18, y: 2 },
        { x: 18, y: 3 },
        { x: 18, y: 4 },
        { x: 18, y: 5 },
        { x: 17, y: 5 },
        { x: 16, y: 5 },
        { x: 15, y: 5 },
        { x: 14, y: 5 },
        { x: 14, y: 4 },
        { x: 15, y: 4 },
      ],
    },
    {
      key: "memory-2-delay-memory",
      kind: "data",
      from: { moduleKey: "memory-2", portId: "data-east" },
      to: { moduleKey: "delay-memory", portId: "data-west" },
      path: [
        { x: 16, y: 0 },
        { x: 17, y: 0 },
        { x: 17, y: 1 },
        { x: 17, y: 2 },
        { x: 17, y: 3 },
        { x: 16, y: 3 },
        { x: 15, y: 3 },
        { x: 14, y: 3 },
        { x: 14, y: 4 },
        { x: 15, y: 4 },
      ],
    },
    {
      key: "delay-memory-memory",
      kind: "data",
      from: { moduleKey: "delay-memory", portId: "data-east" },
      to: { moduleKey: "memory", portId: "data-west" },
      path: [
        { x: 17, y: 4 },
        { x: 18, y: 4 },
        { x: 18, y: 3 },
        { x: 18, y: 2 },
        { x: 17, y: 2 },
        { x: 16, y: 2 },
        { x: 15, y: 2 },
        { x: 14, y: 2 },
        { x: 13, y: 2 },
        { x: 12, y: 2 },
        { x: 11, y: 2 },
        { x: 11, y: 1 },
        { x: 11, y: 0 },
        { x: 12, y: 0 },
      ],
    },
    {
      key: "power-room-cooling",
      kind: "power",
      from: { moduleKey: "power-benchmark", portId: "power-out-south" },
      to: { moduleKey: "room-cooling", portId: "power-in-west" },
      path: [
        { x: 20, y: 1 },
        { x: 20, y: 2 },
        { x: 19, y: 2 },
        { x: 19, y: 3 },
        { x: 19, y: 4 },
        { x: 19, y: 5 },
        { x: 19, y: 6 },
        { x: 19, y: 7 },
        { x: 18, y: 7 },
        { x: 17, y: 7 },
        { x: 17, y: 8 },
        { x: 18, y: 8 },
      ],
    },
    {
      key: "power-arithmetic-5",
      kind: "power",
      from: { moduleKey: "power-benchmark", portId: "power-out-south" },
      to: { moduleKey: "arithmetic-5", portId: "power-in-west" },
      path: [
        { x: 20, y: 1 },
        { x: 20, y: 2 },
        { x: 21, y: 2 },
        { x: 22, y: 2 },
        { x: 23, y: 2 },
        { x: 23, y: 3 },
        { x: 23, y: 4 },
        { x: 23, y: 5 },
        { x: 23, y: 6 },
        { x: 23, y: 7 },
        { x: 23, y: 8 },
        { x: 23, y: 9 },
        { x: 23, y: 10 },
        { x: 23, y: 11 },
        { x: 22, y: 11 },
        { x: 21, y: 11 },
        { x: 20, y: 11 },
        { x: 19, y: 11 },
        { x: 18, y: 11 },
        { x: 18, y: 12 },
        { x: 19, y: 12 },
      ],
    },
    {
      key: "memory-2-arithmetic-5",
      kind: "data",
      from: { moduleKey: "memory-2", portId: "data-east" },
      to: { moduleKey: "arithmetic-5", portId: "data-in-north" },
      path: [
        { x: 16, y: 0 },
        { x: 17, y: 0 },
        { x: 18, y: 0 },
        { x: 19, y: 0 },
        { x: 19, y: 1 },
        { x: 19, y: 2 },
        { x: 19, y: 3 },
        { x: 19, y: 4 },
        { x: 19, y: 5 },
        { x: 19, y: 6 },
        { x: 19, y: 7 },
        { x: 20, y: 7 },
        { x: 21, y: 7 },
        { x: 21, y: 8 },
        { x: 21, y: 9 },
        { x: 21, y: 10 },
        { x: 20, y: 10 },
        { x: 19, y: 10 },
        { x: 19, y: 11 },
        { x: 19, y: 12 },
      ],
    },
    {
      key: "arithmetic-5-memory",
      kind: "data",
      from: { moduleKey: "arithmetic-5", portId: "data-out-east" },
      to: { moduleKey: "memory", portId: "data-west" },
      path: [
        { x: 20, y: 13 },
        { x: 21, y: 13 },
        { x: 21, y: 12 },
        { x: 21, y: 11 },
        { x: 21, y: 10 },
        { x: 21, y: 9 },
        { x: 21, y: 8 },
        { x: 21, y: 7 },
        { x: 21, y: 6 },
        { x: 21, y: 5 },
        { x: 21, y: 4 },
        { x: 21, y: 3 },
        { x: 21, y: 2 },
        { x: 20, y: 2 },
        { x: 19, y: 2 },
        { x: 18, y: 2 },
        { x: 17, y: 2 },
        { x: 16, y: 2 },
        { x: 15, y: 2 },
        { x: 14, y: 2 },
        { x: 13, y: 2 },
        { x: 12, y: 2 },
        { x: 11, y: 2 },
        { x: 11, y: 1 },
        { x: 11, y: 0 },
        { x: 12, y: 0 },
      ],
    },
  ],
  clusterRoles: {
    "task-primary": [
      "memory",
      "memory-2",
      "delay-memory",
      "arithmetic",
      "arithmetic-2",
      "arithmetic-3",
      "arithmetic-4",
      "arithmetic-5",
    ],
    "research-primary": ["memory", "arithmetic", "arithmetic-2"],
    "benchmark-sustained": ["logic", "arithmetic", "arithmetic-2", "arithmetic-3", "arithmetic-4"],
    "benchmark-peak": [
      "logic",
      "arithmetic",
      "arithmetic-2",
      "arithmetic-3",
      "arithmetic-4",
      "arithmetic-5",
    ],
    "blueprint-selection": [
      "arithmetic",
      "arithmetic-2",
      "arithmetic-3",
      "arithmetic-4",
      "room-cooling",
    ],
  } satisfies Readonly<Record<BuildTemplateClusterRole, readonly string[]>>,
};

export const BUILD_TEMPLATES = Object.freeze([
  detachAndFreezeReplayData(STARTER_TEMPLATE),
  detachAndFreezeReplayData(EXPANDED_TEMPLATE),
  detachAndFreezeReplayData(COOLED_TEMPLATE),
] as const);

export const BUILD_TEMPLATE_BY_ID: Readonly<Record<BuildTemplate["id"], BuildTemplate>> =
  Object.freeze({
    "starter-serial": BUILD_TEMPLATES[0],
    "expanded-balanced": BUILD_TEMPLATES[1],
    "cooled-benchmark": BUILD_TEMPLATES[2],
  });

export function getBuildTemplate(id: string): BuildTemplate | undefined {
  return BUILD_TEMPLATE_BY_ID[id as BuildTemplate["id"]];
}

export function resolveBuildTemplateChain(id: BuildTemplate["id"]): readonly BuildTemplate[] {
  const chain: BuildTemplate[] = [];
  let current: BuildTemplate | undefined = getBuildTemplate(id);
  while (current !== undefined) {
    chain.unshift(current);
    current =
      current.baseTemplateId === null ? undefined : getBuildTemplate(current.baseTemplateId);
  }
  return Object.freeze(chain);
}
